act_code: '144166'
requisite: Решение маслихата города Шымкент от 22 июня 2020 года № 67/598-6c. Зарегистрировано Департаментом юстиции города Шымкент 25 июня 2020 года № 113
title:
  rus: О некоторых вопросах проведения мирных собраний
  kaz: Шымкент қаласында бейбіт жиналыстар өткізудің кейбір мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-22
approved_by:
- '167000000002'
version_date:
  kaz: 2023-06-14
  rus: 2023-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/144166/kaz/14.06.2023
  rus: https://zan.gov.kz/client/#!/doc/144166/rus/14.06.2023
caused_by:
  code: '183130'
  requisite: Решение маслихата города Шымкент от 14 июня 2023 года № 4/43-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 20 июня 2023 года № 181-17. Утратило силу решением маслихата города Шымкент от 14 августа 2026 года № 38/342-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в некоторые решения маслихата города Шымкент
    kaz: Шымкент қаласы мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183130/rus
