act_code: '133718'
requisite: Решение маслихата города Шымкент от 16 июля 2019 года № 52/442-6с. Зарегистрировано Департаментом юстиции города Шымкент 31 июля 2019 года № 55
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей города Шымкент с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Шымкент қаласының мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртiбі және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-07-16
approved_by:
- '167000000002'
version_date:
  kaz: 2022-08-12
  rus: 2022-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/133718/kaz/12.08.2022
  rus: https://zan.gov.kz/client/#!/doc/133718/rus/12.08.2022
caused_by:
  code: '171005'
  requisite: Решение маслихата города Шымкент от 12 августа 2022 года № 20/180-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 августа 2022 года № 29248
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 16 июля 2019 года № 52/442-6с «Об утверждении Правил и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов города Шымкент»
    kaz: «Шымкент қаласының мүгедектер қатарындағы мүмкіндігі шектеулі балаларды үйде оқытуға жұмсалған шығындарды өтеудің Қағидалары мен мөлшерін бекіту туралы» 2019 жылғы 16 шілдедегі № 52/442-6с Шымкент қаласы мәслихатының шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171005/rus
