act_code: '133718'
requisite: Решение маслихата города Шымкент от 16 июля 2019 года № 52/442-6с. Зарегистрировано Департаментом юстиции города Шымкент 31 июля 2019 года № 55
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей города Шымкент с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану
  kaz: Шымкент қаласының мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртiбі және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-07-16
approved_by:
- '167000000002'
version_date:
  kaz: 2023-06-14
  rus: 2023-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/133718/kaz/14.06.2023
  rus: https://zan.gov.kz/client/#!/doc/133718/rus/14.06.2023
caused_by:
  code: '183274'
  requisite: Решение маслихата города Шымкент от 14 июня 2023 года № 4/38-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 23 июня 2023 года № 184-17
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 16 июля 2019 года № 52/442-6с «Об определении порядка и размера возмещения затрат на обучение на дому детей города Шымкент с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану»
    kaz: «Шымкент қаласының мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарды өндіріп алу тәртiбі мен мөлшерін айқындау туралы» 2019 жылғы 16 шілдедегі № 52/442-6с Шымкент қаласы мәслихатының шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183274/rus
