act_code: '161856'
requisite: Решение маслихата города Шымкент от 13 декабря 2021 года № 12/92-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25833
title:
  rus: О бюджете города Шымкент на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-13
approved_by:
- '167000000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/161856/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/161856/rus/29.09.2022
caused_by:
  code: '172651'
  requisite: Решение маслихата города Шымкент от 29 сентября 2022 года № 21/185-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 октября 2022 года № 30017
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 13 декабря 2021 года № 12/92-VII «О бюджете города Шымкент на 2022-2024 годы»
    kaz: «2022-2024 жылдарға арналған Шымкент қаласының бюджеті туралы» 2021 жылғы 13 желтоқсандағы № 12/92-VII Шымкент қаласы мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172651/rus
