act_code: '217946'
requisite: Решение маслихата города Шымкент от 28 ноября 2025 года № 30/273-VIII
title:
  rus: Об установлении ставок арендной платы за использование памятников истории и культуры местного значения города Шымкент
  kaz: Шымкент қаласының жергілікті маңызы бар тарих және мәдениет ескерткіштерін пайдаланғаны үшін жалдау ақысының мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-28
approved_by:
- '167000000002'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/217946/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217946/rus/28.11.2025
