act_code: '133447'
requisite: Решение Шымкентского городского маслихата от 27 июня 2019 года № 51/430-6с. Зарегистрировано Департаментом юстиции города Шымкент 19 июля 2019 года № 53
title:
  rus: Об утверждении Правил погребения и организации дела по уходу за могилами в городе Шымкент
  kaz: Шымкент қаласында жерлеу және қабірлерді қарап-күту жөніндегі істі ұйымдастыру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-06-27
approved_by:
- '167000000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/133447/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133447/rus/27.06.2019
