act_code: '133255'
requisite: Решение Шымкентского городского маслихата от 27 июня 2019 года № 51/429-6с. Зарегистрировано Департаментом юстиции города Шымкент 9 июля 2019 года № 52
title:
  rus: Об утверждении Правил о порядке и условиях размещения наружной (визуальной) рекламы на открытом пространстве за пределами помещений, в полосе и вне полосы отвода автомобильных дорог общего пользования на территории города Шымкент
  kaz: Шымкент қаласының аумағында сыртқы (көрнекі) жарнаманы үй-жайлардың шегінен тыс ашық кеңістікте, жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеуінде және белдеуінен тыс жерде орналастыру тәртібі мен шарттары туралы қағидаларды бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-06-27
approved_by:
- '167000000002'
version_date:
  kaz: 2019-06-27
  rus: 2019-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/133255/kaz/27.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133255/rus/27.06.2019
