act_code: '124160'
requisite: Решение Шымкентского городского маслихата от 27 июля 2018 года № 35/280-6с. Зарегистрировано Департаментом юстиции Туркестанской области 3 августа 2018 года № 4705
title:
  rus: О бюджете города Шымкент на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-27
approved_by:
- '167000000002'
version_date:
  kaz: 2018-11-26
  rus: 2018-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/124160/kaz/26.11.2018
  rus: https://zan.gov.kz/client/#!/doc/124160/rus/26.11.2018
caused_by:
  code: '127036'
  requisite: Решение Шымкентского городского маслихата от 26 ноября 2018 года № 41/327-6с. Зарегистрировано Департаментом юстиции города Шымкент 29 ноября 2018 года № 3
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 27 июля 2018 года № 35/280-6с «О бюджете города Шымкент на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Шымкент қаласының бюджеті туралы» Шымкент қаласы мәслихатының 2018 жылғы 27 шілдедегі № 35/280-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127036/rus
