act_code: '130425'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/378-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 29. Утратило силу решением маслихата города Шымкент от 14 августа 2026 года № 38/342-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин города Шымкент»
  kaz: «Шымкент қаласының құрметті азаматы» атағын беру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130425/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/130425/rus/29.03.2019
