act_code: '130425'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/378-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 29. Утратило силу решением маслихата города Шымкент от 14 августа 2026 года № 38/342-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин города Шымкент»
  kaz: «Шымкент қаласының құрметті азаматы» атағын беру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2022-08-12
  rus: 2022-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/130425/kaz/12.08.2022
  rus: https://zan.gov.kz/client/#!/doc/130425/rus/12.08.2022
caused_by:
  code: '170868'
  requisite: Решение маслихата города Шымкент от 12 августа 2022 года № 20/173-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 августа 2022 года № 29173. Утратило силу решением маслихата города Шымкент от 14 августа 2026 года № 38/342-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 29 марта 2019 года № 47/378-6с «Об утверждении Правил присвоения звания «Почетный гражданин города Шымкент»
    kaz: «Шымкент қаласының құрметті азаматы» атағын беру Қағидасын бекіту туралы» 2019 жылғы 29 наурыздағы № 47/378-6с Шымкент қаласы мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170868/rus
