act_code: '133724'
requisite: Решение маслихата города Шымкент от 17 июля 2019 года № 52/444-6с. Зарегистрировано Департаментом юстиции города Шымкент 2 августа 2019 года № 56. Утратило силу решением маслихата города Шымкент от 12 декабря 2025 года № 31/284-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в городе Шымкент
  kaz: Шымкент қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-17
approved_by:
- '167000000002'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/133724/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/133724/rus/27.12.2023
caused_by:
  code: '192078'
  requisite: Решение маслихата города Шымкент от 27 декабря 2023 года № 13/109-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 8 января 2024 года № 200-17. Утратило силу решением маслихата города Шымкент от 12 декабря 2025 года № 31/284-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 17 июля 2019 года № 52/444-6с «Об определении размеров и перечня категорий получателей жилищных сертификатов в городе Шымкент»
    kaz: «Шымкент қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» Шымкент қаласы мәслихатының 2019 жылғы 17 шілдедегі № 52/444-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/192078/rus
