act_code: '125961'
requisite: Решение акима города Шымкент от 14 ноября 2018 года № 9. Зарегистрировано Департаментом юстиции города Шымкент 15 ноября 2018 года № 1
title:
  rus: Об образовании избирательных участков на территории города Шымкент
  kaz: Шымкент қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-14
approved_by:
- '167000000003'
version_date:
  kaz: 2018-11-14
  rus: 2018-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/125961/kaz/14.11.2018
  rus: https://zan.gov.kz/client/#!/doc/125961/rus/14.11.2018
