act_code: '150826'
requisite: Решение маслихата города Шымкент от 15 декабря 2020 года № 72/674-6с. Зарегистрировано Департаментом юстиции города Шымкент 29 декабря 2020 года № 150
title:
  rus: О предоставлении бесплатного проезда гражданам Республики Казахстан, постоянно проживающим в городе Шымкент за пределы населенного пункта для получения высокотехнологичных медицинских услуг в рамках гарантированного объема бесплатной медицинской помощи и (или) медицинской помощи в системе обязательного социального медицинского страхования
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде жоғары технологиялық медициналық көрсетілетін қызметтерді және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде медициналық көмекті алу үшін Шымкент қаласында тұрақты тұратын Қазақстан Республикасының азаматтарына елді мекеннен тысқары жерлерге тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '167000000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150826/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150826/rus/15.12.2020
