act_code: '172479'
requisite: Решение маслихата города Шымкент от 29 сентября 2022 года № 21/194-VII
title:
  rus: Об утверждении Правил содержания и выгула домашних животных в городе Шымкент
  kaz: Шымкент қаласында үй жануарларын ұстау және серуендету қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-29
approved_by:
- '167000000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/172479/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172479/rus/29.09.2022
