act_code: '162338'
requisite: Решение маслихата города Шымкент от 13 декабря 2021 года № 12/98-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26074
title:
  rus: Об утверждении проекта (схемы) зонирования земель города Шымкент
  kaz: Шымкент қаласының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2021-12-13
approved_by:
- '167000000002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/162338/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162338/rus/13.12.2021
