act_code: '146669'
requisite: Решение маслихата города Шымкент от 14 сентября 2020 года № 69/632-6с. Зарегистрировано Департаментом юстиции города Шымкент 24 сентября 2020 года № 127. Утратило силу решением маслихата города Шымкент от 28 марта 2025 года № 25/228-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О ставках платы за негативное воздействие на окружающую среду по городу Шымкент
  kaz: Шымкент қаласы бойынша қоршаған ортаға теріс әсер еткені үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-14
approved_by:
- '167000000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/146669/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146669/rus/14.09.2020
