act_code: '130612'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/383-6с. Зарегистрировано Департаментом юстиции города Шымкент 12 апреля 2019 года № 34. Утратило силу решением маслихата города Шымкент от 25 ноября 2022 года № 22/211-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил отлова и уничтожения бродячих собак и кошек в городе Шымкент
  kaz: Шымкент қаласында қаңғыбас иттер мен мысықтарды аулау және жою қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/130612/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/130612/rus/14.09.2020
caused_by:
  code: '147623'
  requisite: Решение маслихата города Шымкент от 14 сентября 2020 года № 69/633-6с. Зарегистрировано Департаментом юстиции города Шымкент 20 октября 2020 года № 136. Утратило силу решением маслихата города Шымкент от 25 ноября 2022 года № 22/211-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 29 марта 2019 года № 47/383-6с «Об утверждении Правил отлова и уничтожения бродячих собак и кошек в городе Шымкент»
    kaz: «Шымкент қаласында қаңғыбас иттер мен мысықтарды аулау және жою қағидасын бекіту туралы» Шымкент қаласы мәслихатының 2019 жылғы 29 наурыздағы № 47/383-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147623/rus
