act_code: '219351'
requisite: Решение маслихата города Шымкент от 12 декабря 2025 года № 31/275-VIII
title:
  rus: О бюджете города Шымкент на 2026-2028 годы
  kaz: 2026–2028 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-12
approved_by:
- '167000000002'
version_date:
  kaz: 2026-04-23
  rus: 2026-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/219351/kaz/23.04.2026
  rus: https://zan.gov.kz/client/#!/doc/219351/rus/23.04.2026
caused_by:
  code: '224737'
  requisite: Решение маслихата города Шымкент от 23 апреля 2026 года № 35/311-VIII
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 12 декабря 2025 года № 31/275-VIII «О бюджете города Шымкент на 2026-2028 годы»
    kaz: «2026 – 2028 жылдарға арналған Шымкент қаласының бюджеті туралы» Шымкент қаласы мәслихатының 2025 жылғы 12 желтоқсандағы № 31/275-VIII шешіміне өзгерістер енгізу
  link: https://zan.gov.kz/client/#!/doc/224737/rus
