act_code: '140368'
requisite: Решение маслихата города Шымкент от 11 марта 2020 года № 62/536-6с. Зарегистрировано Департаментом юстиции города Шымкент 18 марта 2020 года № 90
title:
  rus: Об утверждении Правил содержания животных на территории города Шымкент
  kaz: Шымкент қаласының аумағында жануарларды асырау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-11
approved_by:
- '167000000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/140368/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/140368/rus/29.09.2022
caused_by:
  code: '172451'
  requisite: Решение маслихата города Шымкент от 29 сентября 2022 года № 21/193-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 октября 2022 года № 29994
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 11 марта 2020 года № 62/536-6с «Об утверждении Правил содержания животных на территории города Шымкент»
    kaz: «Шымкент қаласының аумағында жануарларды асырау қағидасын бекіту туралы» 2020 жылғы 11 наурыздағы № 62/536-6с Шымкент қаласы мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172451/rus
