act_code: '140368'
requisite: Решение маслихата города Шымкент от 11 марта 2020 года № 62/536-6с. Зарегистрировано Департаментом юстиции города Шымкент 18 марта 2020 года № 90
title:
  rus: Об утверждении Правил содержания животных на территории города Шымкент
  kaz: Шымкент қаласының аумағында жануарларды асырау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-11
approved_by:
- '167000000002'
version_date:
  kaz: 2024-08-29
  rus: 2024-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/140368/kaz/29.08.2024
  rus: https://zan.gov.kz/client/#!/doc/140368/rus/29.08.2024
caused_by:
  code: '200537'
  requisite: Решение маслихата города Шымкент от 29 августа 2024 года № 20/172-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 9 сентября 2024 года № 221-17
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 11 марта 2020 года № 62/536-6с «Об утверждении Правил содержания животных на территории города Шымкент»
    kaz: «Шымкент қаласының аумағында жануарларды асырау қағидасын бекіту туралы» Шымкент қаласы мәслихатының 2020 жылғы 11 наурыздағы № 62/536-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200537/rus
