act_code: '219602'
requisite: Решение маслихата города Шымкент от 12 декабря 2025 года № 31/281-VIII
title:
  rus: Об утверждении Программы реновации жилища города Шымкент
  kaz: Шымкент қаласының тұрғын үйді реновациялау бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2025-12-12
approved_by:
- '167000000002'
version_date:
  kaz: 2025-12-12
  rus: 2025-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/219602/kaz/12.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219602/rus/12.12.2025
