act_code: '197869'
requisite: Решение маслихата города Шымкент от 14 июня 2024 года № 17/153-VIII
title:
  rus: Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда (за исключением ставок за древесину, отпускаемую на корню) города Шымкент
  kaz: Шымкент қаласының мемлекеттік орман қоры учаскелерінде орман пайдалану төлемақысының ставкаларын (түбірімен босатылған сүрек үшін белгіленетін ставкаларды қоспағанда) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-14
approved_by:
- '167000000002'
version_date:
  kaz: 2024-06-14
  rus: 2024-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/197869/kaz/14.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197869/rus/14.06.2024
