act_code: '166631'
requisite: Решение маслихата города Шымкент от 30 марта 2022 года № 14/123-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 апреля 2022 года № 27550
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Шымкент
  kaz: Шымкент қаласындағы бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '167000000002'
version_date:
  kaz: 2022-08-12
  rus: 2022-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/166631/kaz/12.08.2022
  rus: https://zan.gov.kz/client/#!/doc/166631/rus/12.08.2022
caused_by:
  code: '170770'
  requisite: Решение маслихата города Шымкент от 12 августа 2022 года № 20/176-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 августа 2022 года № 29171
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 30 марта 2022 года № 14/123-VII «Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Шымкент»
    kaz: «Шымкент қаласындағы бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы» 2022 жылғы 30 наурыздағы № 14/123-VII Шымкент қаласы мәслихатының шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170770/rus
