act_code: '130462'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/393-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 30
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата города Шымкент и о признании утратившим силу решение Шымкентского городского маслихата от 29 мая 2018 года № 28/242-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Шымкентского городского маслихата»
  kaz: «Б» корпусы Шымкент қаласы мәслихаты аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы және Шымкент қалалық мәслихатының 2018 жылғы 29 мамырдағы № 28/242-6с ««Б» корпусы Шымкент қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130462/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/130462/rus/29.09.2022
caused_by:
  code: '172525'
  requisite: Решение маслихата города Шымкент от 29 сентября 2022 года № 21/205-VII. Отменено решением маслихата города Шымкент от 14 июня 2023 года № 4/47-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 29 марта 2019 года № 47/393-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата города Шымкент и о признании утратившим силу решение Шымкентского городского маслихата от 29 мая 2018 года № 28/242-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Шымкентского городского маслихата»
    kaz: «Б» корпусы Шымкент қаласы мәслихаты аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы және Шымкент қалалық мәслихатының 2018 жылғы 29 мамырдағы № 28/242-6с ««Б» корпусы Шымкент қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешімінің күшін жою туралы» 2019 жылғы 29 наурыздағы № 47/393-6с Шымкент қалалық мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172525/rus
