act_code: '130462'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/393-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 30
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата города Шымкент и о признании утратившим силу решение Шымкентского городского маслихата от 29 мая 2018 года № 28/242-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Шымкентского городского маслихата»
  kaz: «Б» корпусы Шымкент қаласы мәслихаты аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы және Шымкент қалалық мәслихатының 2018 жылғы 29 мамырдағы № 28/242-6с ««Б» корпусы Шымкент қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2023-06-14
  rus: 2023-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/130462/kaz/14.06.2023
  rus: https://zan.gov.kz/client/#!/doc/130462/rus/14.06.2023
caused_by:
  code: '183757'
  requisite: Решение маслихата города Шымкент от 14 июня 2023 года № 4/47-VIII
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 29 марта 2019 года № 47/393-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата города Шымкент и о признании утратившим силу решение Шымкентского городского маслихата от 29 мая 2018 года № 28/242-6с «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Шымкентского городского маслихата»
    kaz: «Б» корпусы Шымкент қаласы мәслихаты аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы және Шымкент қалалық мәслихатының 2018 жылғы 29 мамырдағы № 28/242-6с ««Б» корпусы Шымкент қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешімінің күшін жою туралы» 2019 жылғы 29 наурыздағы № 47/393-6с Шымкент қалалық мәслихатының шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183757/rus
