act_code: '219278'
requisite: Решение маслихата города Шымкент от 12 декабря 2025 года № 31/287-VIII
title:
  rus: Об утверждении Положения о государственном учреждении «Ревизионная комиссия по городу Шымкент»
  kaz: «Шымкент қаласы бойынша тексеру комиссиясы» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-12
approved_by:
- '167000000002'
version_date:
  kaz: 2025-12-12
  rus: 2025-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/219278/kaz/12.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219278/rus/12.12.2025
