act_code: '130613'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/384-6с. Зарегистрировано Департаментом юстиции города Шымкент 15 апреля 2019 года № 35. Утратило силу решением маслихата города Шымкент от 25 ноября 2022 года № 22/211-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек в городе Шымкент
  kaz: Шымкент қаласында иттер мен мысықтарды асырау және серуендету қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/130613/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/130613/rus/18.03.2021
caused_by:
  code: '153988'
  requisite: Решение маслихата города Шымкент от 18 марта 2021 года № 3/24-VII. Зарегистрировано Департаментом юстиции города Шымкент 31 марта 2021 года № 161. Утратило силу решением маслихата города Шымкент от 25 ноября 2022 года № 22/211-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 29 марта 2019 года № 47/384-6с «Об утверждении Правил содержания и выгула собак и кошек в городе Шымкент»
    kaz: «Шымкент қаласында иттер мен мысықтарды ұстау және серуендету қағидасын бекіту туралы» Шымкент қаласы мәслихатының 2019 жылғы 29 наурыздағы № 47/384-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153988/rus
