act_code: '130414'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/382-6с. Зарегистрировано Департаментом юстиции города Шымкент 3 апреля 2019 года № 27. Утратило силу решением маслихата города Шымкент от 17 сентября 2025 года № 29/267-VIII (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении Правил общего водопользования в городе Шымкент
  kaz: Шымкент қаласында ортақ су пайдаланудың қағидаларын белгілеу туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130414/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/130414/rus/29.03.2019
