act_code: '127040'
requisite: Решение Шымкентского городского маслихата от 14 декабря 2018 года № 42/334-6с. Зарегистрировано Департаментом юстиции города Шымкент 14 декабря 2018 года № 7
title:
  rus: О бюджете города Шымкент на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-14
approved_by:
- '167000000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127040/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/127040/rus/29.03.2019
caused_by:
  code: '130403'
  requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/365-6с. Зарегистрировано Департаментом юстиции города Шымкент 29 марта 2019 года № 25
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 14 декабря 2018 года № 42/334-6с «О бюджете города Шымкент на 2019-2021 годы»
    kaz: «2019-2021 жылдарға арналған Шымкент қаласының бюджеті туралы» Шымкент қаласы мәслихатының 2018 жылғы 14 желтоқсандағы № 42/334-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130403/rus
