act_code: '130521'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/390-6с. Зарегистрировано Департаментом юстиции города Шымкент 9 апреля 2019 года № 33. Утратило силу решением маслихата города Шымкент от 15 декабря 2020 года № 72/674-6с (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении бесплатного проезда жителям города Шымкент за пределы населенного пункта на лечение за счет бюджетных средств
  kaz: Шымкент қаласының тұрғындарына елді мекен шегінен тыс жерлерге емделуге бюджет қаражаты есебінен тегін жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130521/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/130521/rus/29.03.2019
