act_code: '146670'
requisite: Решение маслихата города Шымкент от 14 сентября 2020 года № 69/629-6с. Зарегистрировано Департаментом юстиции города Шымкент 24 сентября 2020 года № 128. Утратило силу решением маслихата города Шымкент от 12 августа 2022 года № 20/175-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения на территории города Шымкент
  kaz: Шымкент қаласының аумағында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-14
approved_by:
- '167000000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/146670/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146670/rus/14.09.2020
