act_code: '137028'
requisite: Решение маслихата города Шымкент от 11 декабря 2019 года № 58/506-6с. Зарегистрировано Департаментом юстиции города Шымкент 13 декабря 2019 года № 76
title:
  rus: Об определении перечня социально значимых сообщений по городу Шымкент
  kaz: Шымкент қаласы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2019-12-11
approved_by:
- '167000000002'
version_date:
  kaz: 2023-07-03
  rus: 2023-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/137028/kaz/03.07.2023
  rus: https://zan.gov.kz/client/#!/doc/137028/rus/03.07.2023
caused_by:
  code: '183628'
  requisite: Решение маслихата города Шымкент от 3 июля 2023 года № 5/53-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 4 июля 2023 года № 189-17
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 11 декабря 2019 года № 58/506–6с «Об определении перечня социально значимых сообщений по городу Шымкент»
    kaz: «Шымкент қаласы бойынша әлеуметтік мәні бар қатынастардың тізбесін айқындау туралы» 2019 жылғы 11 желтоқсандағы № 58/506–6с Шымкент қаласы мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183628/rus
