act_code: '137028'
requisite: Решение маслихата города Шымкент от 11 декабря 2019 года № 58/506-6с. Зарегистрировано Департаментом юстиции города Шымкент 13 декабря 2019 года № 76
title:
  rus: Об определении перечня социально значимых сообщений по городу Шымкент
  kaz: Шымкент қаласы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2019-12-11
approved_by:
- '167000000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137028/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/137028/rus/12.12.2024
caused_by:
  code: '204588'
  requisite: Решение маслихата города Шымкент от 12 декабря 2024 года № 23/202-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 23 декабря 2024 года № 224-17
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 11 декабря 2019 года № 58/506–6с «Об определении перечня социально значимых сообщений по городу Шымкент»
    kaz: «Шымкент қаласы бойынша әлеуметтік мәні бар қатынастардың тізбесін айқындау туралы» 2019 жылғы 11 желтоқсандағы № 58/506–6с Шымкент қаласы мәслихатының шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204588/rus
