act_code: '137028'
requisite: Решение маслихата города Шымкент от 11 декабря 2019 года № 58/506-6с. Зарегистрировано Департаментом юстиции города Шымкент 13 декабря 2019 года № 76
title:
  rus: Об определении перечня социально значимых сообщений по городу Шымкент
  kaz: Шымкент қаласы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2019-12-11
approved_by:
- '167000000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/137028/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137028/rus/15.12.2020
caused_by:
  code: '150297'
  requisite: Решение маслихата города Шымкент от 15 декабря 2020 года № 72/670-6с. Зарегистрировано Департаментом юстиции города Шымкент 23 декабря 2020 года № 145
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 11 декабря 2019 года № 58/506-6с «Об определении перечня социально значимых сообщений по городу Шымкент»
    kaz: «Шымкент қаласы бойынша әлеуметтік мәні бар қатынастардың тізбесін айқындау туралы» Шымкент қаласы мәслихатының 2019 жылғы 11 желтоқсандағы № 58/506-6с шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150297/rus
