act_code: '130419'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/386-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 28
title:
  rus: Об утверждении положения о награждении Почетной грамотой города Шымкент
  kaz: Шымкент қаласының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2025-12-26
  rus: 2025-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/130419/kaz/26.12.2025
  rus: https://zan.gov.kz/client/#!/doc/130419/rus/26.12.2025
caused_by:
  code: '220737'
  requisite: Решение маслихата города Шымкент от 26 декабря 2025 года № 32/298-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2025 года № 37768
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 29 марта 2019 года № 47/386-6с «Об утверждении положения о награждении Почетной грамотой города Шымкент»
    kaz: «Шымкент қаласының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» Шымкент қаласы мәслихатының 2019 жылғы 29 наурыздағы № 47/386-6с шешiмiне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/220737/rus
