act_code: '130419'
requisite: Решение Шымкентского городского маслихата от 29 марта 2019 года № 47/386-6с. Зарегистрировано Департаментом юстиции города Шымкент 8 апреля 2019 года № 28
title:
  rus: Об утверждении положения о награждении Почетной грамотой города Шымкент
  kaz: Шымкент қаласының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2019-03-29
approved_by:
- '167000000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/130419/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/130419/rus/29.03.2019
