act_code: '194813'
requisite: Решение маслихата города Шымкент от 19 марта 2024 года № 14/123-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 27 марта 2024 года № 202-17
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в городе Шымкент
  kaz: Шымкент қаласында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '167000000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/194813/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/194813/rus/12.12.2024
caused_by:
  code: '204592'
  requisite: Решение маслихата города Шымкент от 12 декабря 2024 года № 23/200-VIII. Зарегистрировано в Департаменте юстиции города Шымкент 24 декабря 2024 года № 225-17
  title:
    rus: О внесении изменения в решение маслихата города Шымкент от 19 марта 2024 года № 14/123-VIII «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в городе Шымкент»
    kaz: «Шымкент қаласында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Шымкент қаласы мәслихатының 2024 жылғы 19 наурыздағы № 14/123-VIII шешiмiне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204592/rus
