act_code: '139512'
requisite: Решение маслихата города Шымкент от 31 января 2020 года № 60/521-6с. Зарегистрировано Департаментом юстиции города Шымкент 12 февраля 2020 года № 85
title:
  rus: Об утверждении Правил благоустройства территории города Шымкент
  kaz: Шымкент қаласының аумағын абаттандыру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-01-31
approved_by:
- '167000000002'
version_date:
  kaz: 2020-12-23
  rus: 2020-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/139512/kaz/23.12.2020
  rus: https://zan.gov.kz/client/#!/doc/139512/rus/23.12.2020
caused_by:
  code: '150507'
  requisite: Решение маслихата города Шымкент от 23 декабря 2020 года № 73/683-6с. Зарегистрировано Департаментом юстиции города Шымкент 25 декабря 2020 года № 149
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 31 января 2020 года № 60/521-6с «Об утверждении Правил благоустройства территории города Шымкент»
    kaz: «Шымкент қаласының аумағын абаттандыру қағидаларын бекіту туралы» Шымкент қаласы мәслихатының 2020 жылғы 31 қаңтардағы № 60/521-6с шешiмiне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150507/rus
