act_code: '139512'
requisite: Решение маслихата города Шымкент от 31 января 2020 года № 60/521-6с. Зарегистрировано Департаментом юстиции города Шымкент 12 февраля 2020 года № 85
title:
  rus: Об утверждении Правил благоустройства территории города Шымкент
  kaz: Шымкент қаласының аумағын абаттандыру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-01-31
approved_by:
- '167000000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/139512/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/139512/rus/14.09.2020
caused_by:
  code: '146842'
  requisite: Решение маслихата города Шымкент от 14 сентября 2020 года № 69/630-6с. Зарегистрировано Департаментом юстиции города Шымкент 29 сентября 2020 года № 130. Утратило силу решением маслихата города Шымкент от 23 декабря 2020 года № 73/683-6с (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 31 января 2020 года № 60/521-6с «Об утверждении Правил благоустройства территории города Шымкент»
    kaz: «Шымкент қаласының аумағын абаттандыру қағидаларын бекіту туралы» Шымкент қаласы мәслихатының 2020 жылғы 31 қантардағы № 60/521-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146842/rus
