act_code: '149942'
requisite: Решение маслихата города Шымкент от 15 декабря 2020 года № 72/651-6с. Зарегистрировано Департаментом юстиции города Шымкент 15 декабря 2020 года № 143
title:
  rus: О бюджете города Шымкент на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '167000000002'
version_date:
  kaz: 2021-09-16
  rus: 2021-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/149942/kaz/16.09.2021
  rus: https://zan.gov.kz/client/#!/doc/149942/rus/16.09.2021
caused_by:
  code: '159881'
  requisite: Решение маслихата города Шымкент от 16 сентября 2021 года № 9/67-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 сентября 2021 года № 24418
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 15 декабря 2020 года № 72/651-6с «О бюджете города Шымкент на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған Шымкент қаласының бюджеті туралы» 2020 жылғы 15 желтоқсандағы № 72/651-6с Шымкент қаласы мәслихатының шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159881/rus
