act_code: '149942'
requisite: Решение маслихата города Шымкент от 15 декабря 2020 года № 72/651-6с. Зарегистрировано Департаментом юстиции города Шымкент 15 декабря 2020 года № 143
title:
  rus: О бюджете города Шымкент на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '167000000002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/149942/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/149942/rus/18.03.2021
caused_by:
  code: '153646'
  requisite: Решение маслихата города Шымкент от 18 марта 2021 года № 3/13-VII. Зарегистрировано Департаментом юстиции города Шымкент 19 марта 2021 года № 158
  title:
    rus: О внесении изменений в решение маслихата города Шымкент от 15 декабря 2020 года № 72/651-6с «О бюджете города Шымкент на 2021-2023 годы»
    kaz: «2021-2023 жылдарға арналған Шымкент қаласының бюджеті туралы» Шымкент қаласы мәслихатының 2020 жылғы 15 желтоқсандағы № 72/651-6с шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153646/rus
